ДЗ 3
Ho1yBot/2024-2-VK-EDU-Frontend-S-Pozolotin pull request #3
Opened 2024-10-10 12:03 UTC by Ho1yBot

# Домашнее задание № 3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @uskov-anton проверить его.

Что было сделано:
* Разбил проект на компоненты
* Вынес отдельную логику
* Не удалось правильно раскидать css файлы по компонентам
* Дизайн не причёсывал

2024-10-12 15:54 UTC, HaseProgram commented
Нужно еще пофиксить конфликты

2024-10-23 17:42 UTC, martinkomitsky requested changes
Нужно исправить конфликт

2024-10-23 17:42 UTC, martinkomitsky commented
@uskov-anton будут комменты?

2024-10-29 06:51 UTC, uskov-anton commented on my-project/simple-chat/src/components/ChatList.js
> +            <form class="form" action="/">
<img width="260" alt="Снимок экрана 2024-10-29 в 10 50 26" src="https://github.com/user-attachments/assets/40faf6d9-5bbe-47f5-975d-ab565ce9fc5c">

Нужно поправить верстку формы, когда много сообщений

2024-10-29 06:55 UTC, uskov-anton commented on my-project/simple-chat/src/index.css
> +.chat-container {
Думаю стили на одни и те же селекторы лучше сосредотачивать в одно месте (компоненте), а не разделять по нескольким файлам

2024-10-29 06:56 UTC, uskov-anton commented on my-project/simple-chat/src/index.css
>  .message-container {
Во flex-контейнерах вместо margin отступы лучше задавать через gap

2024-10-29 06:59 UTC, uskov-anton commented on my-project/simple-chat/src/components/ChatList.js
> +        const lastMessage = messages.length > 0 ? messages[messages.length - 1] : { text: 'Нет сообщений', time: '' };
После ввода сообщений и возврата к списку по-прежнему отображается, что сообщений нет. Текст пропадает только после обновления браузера.

Давай добавим интерактивности и будем каждый раз проверять на наличие сообщений.

2024-10-29 07:00 UTC, uskov-anton commented on my-project/simple-chat/src/components/ChatList.js
> +                <button class="attach"><img src="./static/images/attach-file-icon.svg" alt="Добавление файла"></button>
Не работает функционал загрузки картинок

2024-10-29 07:01 UTC, uskov-anton commented on my-project/simple-chat/src/components/ChatList.js
> +        form.addEventListener('submit', (event) => {
<img width="753" alt="Снимок экрана 2024-10-29 в 11 01 21" src="https://github.com/user-attachments/assets/a2c87c51-6de1-4753-b90e-159a3a41a453">

нужно поправить ошибку

2024-10-29 07:04 UTC, uskov-anton commented on my-project/simple-chat/src/components/fileUpload.js
> +        // Здесь можно добавить логику обработки файла
В дз2 эта же логика была реализована? Кажется ее нужно было сохранить.

2024-11-04 15:57 UTC, uskov-anton commented on my-project/simple-chat/src/components/ChatList.js
> +        const lastMessage = messages.length > 0 ? messages[messages.length - 1] : { text: 'Нет сообщений', time: '' };
Не реализована обратная ситуация, когда очищается список сообщений, то после возврата к сиску чатов нужно указать, что сообщений нет.

2024-11-04 16:00 UTC, uskov-anton commented on my-project/simple-chat/src/components/message.js
> +        contentElement.appendChild(imgElement);
<img width="263" alt="Снимок экрана 2024-11-04 в 19 58 47" src="https://github.com/user-attachments/assets/c18b4682-00ec-4315-a4a5-d126adc0c3f8">

Нужно добавить масштабирование для картинок по размерам контейнера сообщений иначе при больших размерах верстка разъезжается

2024-11-04 16:02 UTC, uskov-anton commented on my-project/simple-chat/src/components/message.js
> +    messageElement.classList.add('message-container');
<img width="117" alt="Снимок экрана 2024-11-04 в 20 01 47" src="https://github.com/user-attachments/assets/99f62b93-7f5d-4c8a-8f35-94029cd21740">

кажется сломался вывод многострочного текста, который был реализован в прошлом дз

2024-11-10 11:14 UTC, martinkomitsky commented
@Ho1yBot привет! пожалуйста, добейся апрува у своего ментора на все ДЗ. У тебя накопилось очень много реквестов, пора уже их сокращать

2024-11-11 17:02 UTC, uskov-anton commented on my-project/simple-chat/src/components/ChatList.js
> +        const lastMessage = messages.length > 0 ? messages[messages.length - 1] : { text: 'Нет сообщений', time: '' };
Не могу проверить фикс, т.к. кажется сломался функционал очистки сообщений

2024-11-13 10:26 UTC, nlif-m commented
При использовании браузера firefox 132.0 (64-bit), при отправке сообщения в чате через "Enter" происходит возврат на страницу выбора чата. Если нажимать "мышкой", то вовзрата не происходит.

2024-11-13 16:45 UTC, uskov-anton approved these changes

2024-11-15 09:49 UTC, martinkomitsky approved these changes

2024-11-15 09:49 UTC, merged

2024-11-15 09:49 UTC, martinkomitsky commented
12!