ДЗ 4
Ho1yBot/2024-2-VK-EDU-Frontend-S-Pozolotin pull request #4
Opened 2024-10-17 09:16 UTC by Ho1yBot

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @uskov-anton проверить его.

Что было сделано:
* Использовал новые для себя технологии CSS
* Добавил анимации
* Добавил транзишены
* Установил viewport
* Добавил функционал по добавлению файлов

2024-10-27 18:18 UTC, martinkomitsky requested changes
Fix конфликты, пожалуйста

2024-11-15 09:51 UTC, martinkomitsky commented
> Fix конфликты, пожалуйста

2024-11-19 14:55 UTC, martinkomitsky commented
@uskov-anton ждём комменты

2024-11-26 17:28 UTC, uskov-anton approved these changes

2024-11-28 18:55 UTC, martinkomitsky approved these changes

2024-11-28 18:56 UTC, merged

2024-11-28 18:56 UTC, martinkomitsky commented
12!