ДЗ 5
Ho1yBot/2024-2-VK-EDU-Frontend-S-Pozolotin pull request #5
Opened 2024-10-24 17:30 UTC by Ho1yBot

# Домашнее задание № 5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @uskov-anton проверить его.

Что было сделано:
* Перенёс бОльшую часть проекта на React
* Познакомился с Vite

2024-10-27 18:18 UTC, martinkomitsky requested changes, later dismissed
И тут конфликты надо тоже починить.

2024-11-19 14:57 UTC, martinkomitsky commented
@Ho1yBot привет! позаботься о том, чтобы все PR с домашними заданиями были без конфликтов. Для этого надо поочерёдно исправить конфликты в каждом дз и влить в следующее. Например, недавно ты починил конфликт в ДЗ 4. Теперь ты можешь влить в ветку ДЗ 5 ветку ДЗ 4 и решить конфликты там, так далее, до последнего.
После этого свяжись с ментором и добейся обратной связи. Нужно продолжать двигать

2024-12-02 12:28 UTC, uskov-anton commented on my-project/simple-chat/webpack.config.js
> +                test: /shadow\.css$/,
По идеи в simple-chat не должно быть правок. Они случайно не из дз4 пришли (тогда надо актуализировать мастер ветку)

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/package.json
> +}
<img width="982" alt="Снимок экрана 2024-12-02 в 15 50 01" src="https://github.com/user-attachments/assets/dcffbc8f-d272-43a1-87b0-308b6efb7302">

нужно добавить

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/components/AttachFile/AttachFile.jsx
> +      <button className={styles.attach} onClick={(e) => { e.preventDefault(); toggleAttach(); }}><img src="./images/attach-file-icon.svg" alt="Прикрепить файл" /></button>
<img width="806" alt="Снимок экрана 2024-12-02 в 15 51 48" src="https://github.com/user-attachments/assets/e9d26ca9-bef4-446d-932d-d3f07ef7de87">

Нужно везде заменить иконки (вместо кастомных svg на библиотечные)

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/components/AttachFile/AttachFile.jsx
> +import FileUpload from "./../FileUpload/FileUpload";
Давай везде `./../ ` сократим до `../`

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/components/ChatList/ChatList.jsx
> +  const [chats, setChats] = useState([
Если `setChats` не используется, то его объявлять не обязательно

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/App.jsx
> +        onClearMessages={clearTrigger}
Свойства с приставкой `on` обычно используются только для обработчиков событий. Поэтому здесь стоит переименовать свойство (например в `сlearMessages`)

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/components/Chat/Chat.jsx
> +// export default Chat;
Если этот компонент не нужен, то давай уберем его.

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/components/Message/Message.jsx
> +// components/Message/Message.jsx
Нужно переименовать компонент (упущено множественное число)

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/components/ChatList/ChatList.jsx
> +                  <p>{lastMessage.text}</p>
Запустил локально приложение (сообщений нет). 

Добавил сообщение в первый чат. Вернулся к списку. У второго чата последним отображается сообщение из первого чата:

<img width="240" alt="Снимок экрана 2024-12-02 в 16 19 53" src="https://github.com/user-attachments/assets/356c26d4-0488-46ce-bd95-87ddcb29ef23">

Если перейти во второй чат, в котором нет сообщений, и вернутся в список, то отображается у первого чата отсутствие сообщений:

<img width="241" alt="Снимок экрана 2024-12-02 в 16 19 59" src="https://github.com/user-attachments/assets/fa8206b5-714b-4b4a-9d11-825d4416935b">

нужно поправить

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/components/ChatList/ChatList.jsx
> +                  <p>{lastMessage.text}</p>
Для картинок ничего не отображается. Давай выводить название файла для lastMessage

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/components/AttachFile/AttachFile.jsx
> +              <button onClick={(e) => { e.preventDefault(); onFileSelect(); }}>Choose from gallery</button>
При ховере текст скачет. Давай его выводить одинаково в обоих случаях

<img width="92" alt="Снимок экрана 2024-12-02 в 16 21 23" src="https://github.com/user-attachments/assets/6e84cb4d-e968-462a-94d5-dfac43cc346d">

<img width="88" alt="Снимок экрана 2024-12-02 в 16 21 27" src="https://github.com/user-attachments/assets/d7afcab2-51c1-4af9-bd22-9f2304050594">

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/components/Message/Message.jsx
> +            </div>
Давай картинки выводить как картинки, а скачивание только для не картинок

<img width="127" alt="Снимок экрана 2024-12-02 в 16 21 48" src="https://github.com/user-attachments/assets/c24eb94a-3209-4e2f-b830-d8ef1559053a">

2024-12-02 12:28 UTC, uskov-anton commented on react-chat/src/components/ChatList/ChatList.jsx
> +          <MessageForm
При большом кол-ве сообщений, форма уезжает с экрана за границы. Давай скрол будет только у контейнера с сообщениями. Таким образом форма всегда будет отображаться на экране.

<img width="265" alt="Снимок экрана 2024-12-02 в 16 25 21" src="https://github.com/user-attachments/assets/364cd932-c030-406d-8f66-25221214aaf4">

2024-12-16 19:29 UTC, uskov-anton commented on my-project/simple-chat/webpack.config.js
> +                test: /shadow\.css$/,
Комментарий все еще актуальный

2024-12-16 19:29 UTC, uskov-anton commented on react-chat/src/components/AttachFile/AttachFile.jsx
> +      <button className={styles.attach} onClick={(e) => { e.preventDefault(); toggleAttach(); }}><img src="./images/attach-file-icon.svg" alt="Прикрепить файл" /></button>
Комментарий все еще актуальный

2024-12-16 19:32 UTC, uskov-anton commented on react-chat/src/components/Message/Message.jsx
> +// components/Message/Message.jsx
Давай здесь в комментарии и в названии директории тоже поправим

2024-12-16 19:34 UTC, uskov-anton commented on react-chat/src/components/ChatList/ChatList.jsx
> +          console.log(lastMessage);
Нужно не забывать убирать подобный код при финальном коммите

2024-12-16 19:37 UTC, uskov-anton commented on react-chat/src/components/ChatList/ChatList.jsx
> +  }, [clearMessages]);
Если clearMessages был true, а потом станет false, то эффект сработает и очистит сообщения. В результате снаружи будет не совсем ожидаемое поведение. Давай очистку добавим только, если значение положительное во флаге

2024-12-23 06:59 UTC, HaseProgram commented on react-chat/src/App.jsx
> +  const [clearTrigger, setClearTrigger] = useState(false); // Триггер для перерисовки
Рабочая тема в итоге, но добавлю, что несмотря на то, что эти дз без глобального стора, ничего не мешает нам использовать подход, когда глобальные данные у нас хранятся где-то на верхнем уровне и "спускаются вниз".  Если бы мы инициализировали массив с сообщениями на уровне App.jsx (или где-то в отдельном файле и просто подключили его сюда), то не пришлось бы спускать вниз триггеры и методы их установки. Достаточно было бы передать в Menu.jsx метод очистки сообщений и все :)

2024-12-23 07:00 UTC, HaseProgram submitted a review, later dismissed
В целом ОК, готов ставить аппрув и мержу

2024-12-23 07:01 UTC, HaseProgram approved these changes
12!

2024-12-23 07:01 UTC, merged