ДЗ 6
Ho1yBot/2024-2-VK-EDU-Frontend-S-Pozolotin pull request #6
Opened 2024-11-03 12:07 UTC by Ho1yBot

# Домашнее задание № 6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @uskov-anton проверить его.

Что было сделано:
* Изучен React Router 
* Настроил клиентскую маршрутизацию для своих страниц
* Сверстал страницу профиля

2024-12-23 07:17 UTC, HaseProgram commented on react-chat/src/App.jsx
> +            />
Здесь уже стоит сделать чат отдельным компонентом. Как минимум - это не список чатов. Как максимум затрудняется навигация по истории. Сейчас не работают стрелочки истории в браузере. Да и если перезагрузить страницу при открытом чате, откроется список всех чатов (так как не устанавливается переменная `currentChatID`).

Я предлагаю
1) Сделать отдельный компонент для чата
2) На роут `/chat/:chatId` показывать новый компонент
3) В компоненте отдельного чата при маунте проверять урл и именно из УРЛА доставать текущий ID чата (то есть вручную не передавать в компонент).

2024-12-23 07:25 UTC, HaseProgram requested changes
1) Подтянуть мастер
2) Пофиксить конфликты
3) Пофиксить коммент

В остальном ок - как сделаешь - можешь написать в ЛС, смержу

2024-12-23 07:42 UTC, HaseProgram commented on react-chat/src/App.jsx
> +  const openProfile = (userId) => {
Кажется не круто подобные методы прокидывать как параметры.
Можно либо на месте делать `onClick = () => navigate(...)` либо (если хочется, чтобы было централизованно) вынести подобные методы в отдельный файл с роутингом и экспортить оттуда, где это необходимо

2024-12-29 13:08 UTC, martinkomitsky commented
+ исправить конфликты

2025-01-01 19:59 UTC, martinkomitsky commented
@HaseProgram фиксы можно смотреть

2025-01-12 19:09 UTC, HaseProgram approved these changes, later dismissed

2025-01-12 19:10 UTC, HaseProgram approved these changes

2025-01-12 19:10 UTC, merged